import { active, activeProjects, aiLog, calendarAhead, d, iso, items, meetings, pastMeetings, people, programs, projChip, projects, sweepTriggers, wiki } from '../data/example.js';
import { TODAY } from '../lib/dates.js';
import { activity, by, days, delegated, esc, fmtDate, initials, mine, mine_, pname, projName, until, wikiLint } from '../model.js';
import { I, projHealth } from '../ui/nav.js';
import { waitingRow } from './now.js';

  <div class="people"><div class="pcard aicard"><div class="top"><span class="av">AI</span><div><div><b>Assistant</b></div><div class="role">Delegate · works from the ledger · never sends unasked</div></div></div>
    <div class="two"><div><div class="h">They owe me · ${delegated('queued').length + delegated('working').length}</div><ul>${[...delegated('working'), ...delegated('queued')].map(x => `<li>${esc(x.next)} <span class="age">${x.del.status}</span></li>`).join('') || '<li class="faint">Nothing in progress</li>'}</ul></div>
    <div><div class="h">I owe them · ${delegated('ready').length} reviews</div><ul>${delegated('ready').map(x => `<li>${esc(x.next)}</li>`).join('') || '<li class="faint">Nothing to review</li>'}</ul></div></div>
    <div class="foot"><span>${aiLog.length} runs this week</span><a class="btn sm ghost" href="#delegated">Delegated ledger</a></div></div>
  ${people.map(p => { const theirs = by('waiting').filter(w => w.owner === p.id); const mine = mine_().filter(a => a.ctx === '@1:1/' + p.id || (a.next.toLowerCase().includes(p.name.split(' ')[0].toLowerCase())));
    return `<div class="pcard"><div class="top"><span class="av">${initials(p.id)}</span><div><div><b>${esc(p.name)}</b></div><div class="role">${esc(p.role)}</div></div></div>
    <div class="two"><div><div class="h">They owe me · ${theirs.length}</div><ul>${theirs.map(w => `<li class="${until(w.followUp) < 0 ? 'over' : ''}">${esc(w.next)} <span class="age">${days(w.since)}d</span></li>`).join('') || '<li class="faint">Nothing open</li>'}</ul></div>
    <div><div class="h">I owe them · ${mine.length}</div><ul>${mine.map(a => `<li>${esc(a.next)}</li>`).join('') || '<li class="faint">Nothing open</li>'}</ul></div></div>
    <div class="foot"><span>Last touched ${days(p.lastTouched)}d ago</span><button class="btn sm ghost" data-agenda="${p.id}">1:1 agenda · ${p.agenda.length}</button></div></div>`; }).join('')}</div>`;
}

export function viewReview() {
  const inbox = by('inbox').length, noNext = projects.filter(p => !p.dropped && !programs.find(g => g.id === p.program)?.retired && projHealth(p).noNext), aged = by('waiting').filter(w => days(w.since) > 14), some = by('someday'), done = by('done');
  const steps = [
    { id:'inbox', title:'Get the inbox to zero', auto: inbox === 0, status: inbox ? `${inbox} left` : 'Empty', body: inbox ? `<div class="row"><div class="t">${inbox} item${inbox > 1 ? 's' : ''} still need a decision.</div><a class="btn sm" href="#inbox">Open inbox</a></div>` : `<div class="row"><div class="t muted">Nothing unclarified. Good.</div></div>` },
    { id:'sweep', title:'Mind sweep — empty your head', status: `${items.filter(i => i.source === 'sweep' && i.captured && days(i.captured) === 0).length} captured today`, body: `<div class="row"><div class="t"><div class="muted" style="margin-bottom:6px">Walk the triggers; capture anything that surfaces. Don't clarify yet — that's the inbox's job.</div><div class="trig">${sweepTriggers.map(t => `<span class="chip">${esc(t)}</span>`).join('')}</div></div></div><div class="row"><form class="capture" data-sweepform style="max-width:none;flex:1"><span class="faint">+</span><input placeholder="What's on your mind?" aria-label="Mind sweep capture"><span class="hint">⏎</span></form></div>` },
    { id:'pastcal', title:'Sweep last week\'s calendar', status: `${pastMeetings.filter(m => !m.captured).length} meetings with nothing captured`, body: pastMeetings.map(m => `<div class="row"><div class="t"><div>${esc(m.title)}</div><div class="m"><span class="faint">${fmtDate(m.on)} · ${m.who.map(pname).join(', ')}</span>${m.captured ? `<span class="chip">${m.captured} captured</span>` : '<span class="flag">nothing captured</span>'}</div></div>${m.captured ? '' : `<button class="btn sm" data-capfrom="${esc(m.title)}">Capture follow-ups</button>`}</div>`).join('') + `<div class="row"><div class="t muted">A meeting with no captured items usually means loose ends in your head, not a meeting with none.</div></div>` },
    { id:'upcoming', title:'Preview the next two weeks', status: `${calendarAhead.length + mine().filter(a => a.hard && until(a.hard) > 0 && until(a.hard) <= 14).length} on the calendar`, body: [...calendarAhead.map(c => ({ on:c.on, txt:`${c.time} ${c.title}`, sub:c.who.map(pname).join(', '), mtg:true })), ...mine().filter(a => a.hard && until(a.hard) > 0 && until(a.hard) <= 14).map(a => ({ on:a.hard, txt:a.next, sub:projName(a.project), mtg:false }))].sort((a, b) => a.on - b.on).map(e => `<div class="row"><div class="t"><div>${esc(e.txt)}${e.mtg ? '' : ' <span class="chip" style="color:var(--warn);background:var(--warn-soft)">day-specific action</span>'}</div><div class="m"><span class="faint">${fmtDate(e.on)} · ${esc(e.sub)}</span></div></div>${e.mtg ? `<button class="btn sm ghost" data-capprep="${esc(e.txt.replace(/^\d\d:\d\d /, ''))}|${iso(e.on)}">Capture prep</button>` : ''}</div>`).join('') + `<div class="row"><div class="t"><div class="muted" style="margin-bottom:6px">Anything here that needs prep you haven't got a next action for? Capture it now — it goes to the inbox to clarify.</div><form class="capture" data-sweepform="calendar" style="max-width:none"><span class="faint">+</span><input placeholder="e.g. Pull savings numbers before board prep with Ingrid" aria-label="Capture prep"><span class="hint">⏎</span></form></div></div>` },
    { id:'next', title:'Every project has a next action', auto: noNext.length === 0, status: noNext.length ? `${noNext.length} missing` : 'All covered', body: noNext.map(p => `<div class="row"><div class="t"><div>${esc(p.name)}</div><div class="m">${projChip(p.program)}<span class="age over">${projHealth(p).lm ? projHealth(p).age + 'd since movement' : 'no activity'}</span></div></div><button class="btn sm" data-proj="${p.id}">Decide next action</button></div>`).join('') || `<div class="row"><div class="t muted">Every active project has an action or a waiting-for.</div></div>` },
    { id:'waiting', title:'Review waiting-fors older than 14 days', status: `${aged.length} aged`, body: aged.map(w => waitingRow(w, { showOwner:true })).join('') },
    { id:'someday', title:'Someday / maybe: promote or drop', status: `${some.length} parked`, body: some.map(s => `<div class="row"><div class="t"><div>${esc(s.next)}</div><div class="m"><span class="age">${days(s.since)}d parked</span></div></div><button class="btn sm" data-promote="${s.id}">Promote</button><button class="btn sm ghost" data-drop="${s.id}">Drop</button></div>`).join('') },
    { id:'wins', title:'Wins this week → status draft', status: `${done.length} done`, body: done.map(x => `<div class="row"><div class="t"><div>${esc(x.next)}</div><div class="m">${projChip(x.project)}<span class="faint">${fmtDate(x.doneAt || TODAY)}</span></div></div></div>`).join('') + `<div class="row"><div class="t muted">These become the "done" section of Friday's status.</div><button class="btn sm" data-status>Draft status report</button></div>` },
    { id:'ai', title:'Audit what the AI did this week', status: `${aiLog.length} runs · ${items.filter(i => i.del?.status === 'approved').length + 3} approved`, body: aiLog.map(l => `<div class="row"><div class="t"><div>${esc(l.what)}</div><div class="m"><span class="chip ${l.mode === 'auto' ? 'aichip' : ''}">${l.mode === 'auto' ? 'automatic' : 'you approved'}</span><span class="faint">${fmtDate(l.at)}</span></div></div></div>`).join('') + `<div class="row"><div class="t muted">Automatic actions are the ones to eyeball: if any look wrong, lower that capability's autonomy.</div><a class="btn sm" href="#delegated">Autonomy settings</a></div>` },
    { id:'lint', title:'Wiki lint', status: `${wikiLint.length} findings`, body: wikiLint.map(l => `<div class="row"><div class="t"><div>${esc(l.what)}</div><div class="m"><span class="chip mono">${esc(l.page)}.md</span><span class="faint">${esc(l.fix)}</span></div></div></div>`).join('') + `<div class="row"><div class="t muted">Stale compiled sections, wiki–ledger contradictions, orphan pages. Fixes go through a reviewed ingest.</div></div>` },
    { id:'horizons', title:'Look up: programs still serve their purpose?', status: `${active().length} programs`, body: active().map(g => `<div class="row"><div class="t"><div>${esc(g.name)}</div><div class="m muted">${esc(g.purpose)}</div><div class="m"><span class="faint num">${activeProjects(g.id).length} projects · sponsor ${esc(pname(g.sponsor))}</span></div></div><button class="btn sm ghost" data-retire="${g.id}">Retire</button></div>`).join('') + `<div class="row"><div class="t muted">A program is an area of responsibility: rare, deliberate, with a purpose you can check projects against. Add one here or from Programs; retire one when its purpose is met.</div><button class="btn sm" data-addprog>Add program</button></div>` },
  ];
  const why = {
    inbox: 'Get clear. Nothing else in the review is trustworthy while unclarified items are sitting here — an unprocessed inbox is a list of decisions you haven\'t made yet. Empty it first, then review.',
    sweep: 'Get clear. Anything still in your head is not in the system, and GTD only works if the system holds everything. Walk the triggers and write down whatever surfaces, without judging or clarifying it — capture now, decide later in the inbox.',
    pastcal: 'Get current. Meetings generate commitments that rarely get written down in the moment. A meeting with nothing captured usually means loose ends in your head, not a meeting with none — look at each and capture what you promised or were promised.',
    upcoming: 'Get current. Look two weeks ahead so nothing arrives unprepared. Anything that needs prep and doesn\'t yet have a next action is a gap — capture it here and clarify it in the inbox.',
    next: 'Get current. The projects list only moves if every project has a next physical action or a waiting-for. A project without one is stalled, however healthy it looks — decide the action now, or park or drop the project honestly.',
    waiting: 'Get current. What\'s owed to you drives your programs more than your own list does. For each aged item ask: still needed? If yes, nudge or escalate; if no, drop it. Don\'t let a waiting-for quietly become a wish.',
    someday: 'Get creative. Someday / maybe is where ideas incubate without cluttering the action lists — but only if you actually look at them. Promote what\'s ready, give a revisit date to what isn\'t, drop what no longer interests you.',
