import { aiLog, calendarAhead, items, pastMeetings, programs, projects, sweepTriggers, wikiLint } from '../data/example.js';
import { TODAY, d, days, fmtDate, iso, until } from '../lib/dates.js';
import { esc } from '../lib/dom.js';
import { active, activeProjects, by, mine, pname, projHealth, projName } from '../model.js';
import { state } from '../state.js';
import { projChip, waitingRow } from '../ui/fragments.js';

export function viewReview() {
  const inbox = by('inbox').length, noNext = projects.filter(p => !p.dropped && !programs.find(g => g.id === p.program)?.retired && projHealth(p).noNext), aged = by('waiting').filter(w => days(w.since) > 14), some = by('someday'), done = by('done');
  const steps = [
    { id:'inbox', title:'Get the inbox to zero', auto: inbox === 0, status: inbox ? `${inbox} left` : 'Empty', body: inbox ? `<div class="row"><div class="t">${inbox} item${inbox > 1 ? 's' : ''} still need a decision.</div><a class="btn sm" href="#inbox">Open inbox</a></div>` : `<div class="row"><div class="t muted">Nothing unclarified. Good.</div></div>` },
    { id:'sweep', title:'Mind sweep — empty your head', status: `${items.filter(i => i.source === 'sweep' && i.captured && days(i.captured) === 0).length} captured today`, body: `<div class="row"><div class="t"><div class="muted">Walk the triggers: ${esc(sweepTriggers.map(t => t.replace(/^./, c => c.toLowerCase())).join('; '))}. Capture anything that surfaces; don't clarify yet — that's the inbox's job.</div></div></div><div class="row"><form class="capture" data-sweepform style="max-width:none;flex:1"><span class="faint">+</span><input placeholder="What's on your mind?" aria-label="Mind sweep capture"><span class="hint">⏎</span></form></div>` },
    { id:'pastcal', title:'Sweep last week\'s calendar', status: `${pastMeetings.filter(m => !m.captured).length} meetings with nothing captured`, body: pastMeetings.map(m => `<div class="row"><div class="t"><div>${esc(m.title)}</div><div class="m"><span class="faint">${fmtDate(m.on)} · ${m.who.map(pname).join(', ')}</span>${m.captured ? `<span class="chip">${m.captured} captured</span>` : '<span class="flag">nothing captured</span>'}</div></div>${m.captured ? '' : `<button class="btn sm" data-capfrom="${esc(m.title)}">Capture follow-ups</button>`}</div>`).join('') + `<div class="row"><div class="t muted">A meeting with no captured items usually means loose ends in your head, not a meeting with none.</div></div>` },
    { id:'upcoming', title:'Preview the next two weeks', status: `${calendarAhead.length + mine().filter(a => a.hard && until(a.hard) > 0 && until(a.hard) <= 14).length} on the calendar`, body: (() => { /* 14-day grid: meetings (dashed, click to capture prep), day-specific actions (warn), soft dues (neutral), ticklers (accent). */
      const all = mine();
      return `<div class="cal two-weeks">${[...Array(14)].map((_, i) => { const day = d(i), dow = day.getDay(), wk = dow === 0 || dow === 6;
        const ms = calendarAhead.filter(c => until(c.on) === i), hs = all.filter(a => a.hard && until(a.hard) === i), ds = all.filter(a => !a.hard && a.due && until(a.due) === i), ts = items.filter(x => (x.kind === 'someday' || x.kind === 'reference') && x.revisit && until(x.revisit) === i);
        return `<div class="cal-col ${i === 0 ? 'today' : ''} ${wk ? 'wk' : ''}"><div class="cal-h"><b>${i === 0 ? 'Today' : day.toLocaleDateString('en-GB', { weekday:'short' })}</b><span>${day.getDate()}</span></div>${ms.map(m => `<button class="cal-item mtg" data-capprep="${esc(m.title)}|${iso(m.on)}" title="Capture prep for ${esc(m.title)}">${m.time}<span>${esc(m.title)}</span></button>`).join('')}${hs.map(a => `<button class="cal-item hard" data-item="${a.id}" title="${esc(a.next)}">${esc(a.next)}<span>${esc(projName(a.project))}</span></button>`).join('')}${ds.map(a => `<button class="cal-item" data-item="${a.id}" title="Due: ${esc(a.next)}">${esc(a.next)}<span>due · ${esc(projName(a.project))}</span></button>`).join('')}${ts.map(t => `<div class="cal-item tick" title="Tickler: ${esc(t.next)}">↺ ${esc(t.next)}<span>resurfaces</span></div>`).join('')}</div>`; }).join('')}</div>`; })() + `<div class="row"><div class="t"><div class="muted" style="margin-bottom:6px">Click a meeting to capture prep for it. Anything else here that needs prep you haven't got a next action for? Capture it now — it goes to the inbox to clarify.</div><form class="capture" data-sweepform="calendar" style="max-width:none"><span class="faint">+</span><input placeholder="e.g. Pull savings numbers before board prep with Ingrid" aria-label="Capture prep"><span class="hint">⏎</span></form></div></div>` },
    { id:'next', title:'Every project has a next action', auto: noNext.length === 0, status: noNext.length ? `${noNext.length} missing` : 'All covered', body: (noNext.map(p => `<div class="row"><div class="t"><div>${esc(p.name)}</div><div class="m">${projChip(p.program)}<span class="age over">${projHealth(p).lm ? projHealth(p).age + 'd since movement' : 'no activity'}</span></div></div><button class="btn sm" data-proj="${p.id}">Decide next action</button></div>`).join('') || `<div class="row"><div class="t muted">Every active project has an action or a waiting-for.</div></div>`) + `<div class="row"><div class="t"><div class="muted" style="margin-bottom:6px">Quick intake — add a next action straight to a project without going through the inbox.</div><div class="quickadd"><select class="in" aria-label="Project">${active().map(g => `<optgroup label="${esc(g.name)}"><option value="${g.id}">${esc(g.name)} — program level</option>${activeProjects(g.id).map(j => `<option value="${j.id}">${esc(j.name)}</option>`).join('')}</optgroup>`).join('')}</select><input class="in" placeholder="Verb first: 'Email Dana to pick a retro date'" aria-label="Next action"><input class="in" type="number" min="1" value="20" aria-label="Minutes" title="Minutes — 15 or less files as @quick"><button class="btn sm primary" data-quickadd>Add action</button></div></div></div>` },
    { id:'waiting', title:'Review waiting-fors older than 14 days', status: `${aged.length} aged`, body: aged.map(w => waitingRow(w, { showOwner:true })).join('') },
    { id:'someday', title:'Someday / maybe: promote or drop', status: `${some.length} parked`, body: some.map(s => `<div class="row"><div class="t"><div>${esc(s.next)}</div><div class="m"><span class="age">${days(s.since)}d parked</span></div></div><button class="btn sm" data-promote="${s.id}">Promote</button><button class="btn sm ghost" data-drop="${s.id}">Drop</button></div>`).join('') },
    { id:'wins', title:'Wins this week → status draft', status: `${done.length} done`, body: done.map(x => `<div class="row"><div class="t"><div>${esc(x.next)}</div><div class="m">${projChip(x.project)}<span class="faint">${fmtDate(x.doneAt || TODAY)}</span></div></div></div>`).join('') + `<div class="row"><div class="t muted">These become the "done" section of Friday's status.</div><button class="btn sm" data-status>Draft status report</button></div>` },
    { id:'ai', title:'Audit what the AI did this week', status: `${aiLog.length} runs · ${items.filter(i => i.del?.status === 'approved').length + 3} approved`, body: `<div class="row"><div class="t muted">Everything the assistant touched this week, as it happened.</div><button class="btn sm" data-goflow="ai">Watch in Flow</button></div>` + aiLog.map(l => `<div class="row"><div class="t"><div>${esc(l.what)}</div><div class="m"><span class="chip ${l.mode === 'auto' ? 'aichip' : ''}">${l.mode === 'auto' ? 'automatic' : 'you approved'}</span><span class="faint">${fmtDate(l.at)}</span></div></div></div>`).join('') + `<div class="row"><div class="t muted">Automatic actions are the ones to eyeball: if any look wrong, lower that capability's autonomy.</div><a class="btn sm" href="#delegated">Autonomy settings</a></div>` },
    { id:'lint', title:'Wiki lint', status: `${wikiLint.length} findings`, body: wikiLint.map(l => `<div class="row"><div class="t"><div>${esc(l.what)}</div><div class="m"><span class="chip mono">${esc(l.page)}.md</span><span class="faint">${esc(l.fix)}</span></div></div></div>`).join('') + `<div class="row"><div class="t muted">Stale compiled sections, wiki–ledger contradictions, orphan pages. Fixes go through a reviewed ingest.</div></div>` },
    { id:'horizons', title:'Look up: programs still serve their purpose?', status: `${active().length} programs`, body: active().map(g => `<div class="row"><div class="t"><div>${esc(g.name)}</div><div class="m muted">${esc(g.purpose)}</div><div class="m"><span class="faint num">${activeProjects(g.id).length} projects · sponsor ${esc(pname(g.sponsor))}</span></div></div><button class="btn sm ghost" data-retire="${g.id}">Retire</button></div>`).join('') + `<div class="row"><div class="t muted">A program is an area of responsibility: rare, deliberate, with a purpose you can check projects against. Add one here or from Programs; retire one when its purpose is met.</div><button class="btn sm" data-addprog>Add program</button></div>` },
  ];
  const why = {
    inbox: 'Get clear. Nothing else in the review is trustworthy while unclarified items are sitting here — an unprocessed inbox is a list of decisions you haven\'t made yet. Empty it first, then review.',
    sweep: 'Get clear. Anything still in your head is not in the system, and GTD only works if the system holds everything. Walk the triggers and write down whatever surfaces, without judging or clarifying it — capture now, decide later in the inbox.',
    pastcal: 'Get current. Meetings generate commitments that rarely get written down in the moment. A meeting with nothing captured usually means loose ends in your head, not a meeting with none — look at each and capture what you promised or were promised.',
    upcoming: 'Get current. Look two weeks ahead so nothing arrives unprepared. Anything that needs prep and doesn\'t yet have a next action is a gap — capture it here and clarify it in the inbox.',
    next: 'Get current. The projects list only moves if every project has a next physical action or a waiting-for. A project without one is stalled, however healthy it looks — decide the action now, or park or drop the project honestly.',
    waiting: 'Get current. What\'s owed to you drives your programs more than your own list does. For each aged item ask: still needed? If yes, nudge or escalate; if no, drop it. Don\'t let a waiting-for quietly become a wish.',
    someday: 'Get creative. Someday / maybe is where ideas incubate without cluttering the action lists — but only if you actually look at them. Promote what\'s ready, give a revisit date to what isn\'t, drop what no longer interests you.',
    wins: 'Get current. Completed items are the evidence for status reporting, and they\'re also how you calibrate: if this list is short, either the week was interrupt-driven or the next actions were too big. The draft status report assembles from here plus health and waiting-fors.',
    ai: 'Trust check. Everything the assistant did this week is listed; automatic actions are the ones to eyeball. If something looks wrong, lower that capability\'s autonomy — the settings exist so trust can be adjusted one capability at a time.',
    lint: 'Get current, for the wiki. Compiled status sections go stale, the wiki and the ledger can disagree, pages can go orphaned. Fix findings through a reviewed ingest so the context you rely on for prep briefs stays true.',
    horizons: 'Look up. Programs are areas of responsibility; each has a purpose you can check projects against. Ask: does every project still serve its program\'s purpose? Is there work with no home? Has a program met its purpose and earned retirement?',
  };
  const doneCount = steps.filter(s => s.auto || state.review[s.id]).length;
  return `<div class="vhead"><div><h1>Weekly review</h1><p>AI prepared the evidence; the decisions are yours. Last completed ${days(state.lastReview)} days ago.</p></div><div style="display:flex;align-items:center;gap:12px;min-width:260px"><button class="btn" data-goflow="week" title="Replay the week in Flow">Watch the week</button><div class="progress"><i style="width:${doneCount / steps.length * 100}%"></i></div><span class="note num">${doneCount}/${steps.length}</span></div></div>
  <div class="steps">${steps.map((s, i) => { const ok = s.auto || !!state.review[s.id]; return `<div class="step ${ok ? 'ok' : ''}"><div class="sh"><input class="chk" type="checkbox" data-step="${s.id}" ${ok ? 'checked' : ''} ${s.auto ? 'disabled' : ''}><span class="n">${i + 1}</span><h3>${s.title}</h3><span class="st">${s.status}</span></div>${why[s.id] ? `<div class="swhy">${why[s.id]}</div>` : ''}<div class="sb">${s.body}</div></div>`; }).join('')}</div>
  <div class="acts" style="border:0;padding:0"><span class="note">Completing the review stamps <code class="mono">last_reviewed</code> on every project and resets the health strip.</span><span class="sp"></span><button class="btn primary" data-complete ${doneCount < steps.length ? 'disabled' : ''}>Complete review</button></div>`;
}
